# Generated by Django 5.0.6 on 2024-06-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
