# Generated by Django 5.0.6 on 2024-06-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_usn', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('student_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_topic', models.CharField(max_length=200)),
                ('project_language', models.CharField(max_length=200)),
                ('project_durations', models.IntegerField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.student')),
            ],
        ),
    ]
