# Generated by Django 5.0.6 on 2024-06-21 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0002_course_meeting_student_enrolment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.student'),
        ),
    ]
